# .gitlab-ci.yml
image: golang:latest

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOOS: linux

cache:
  paths:
    - .go/pkg/mod/
    - .go/bin/

stages:
  - test
  - build
  - deploy

before_script:
  - mkdir -p .go
  - export PATH=$GOPATH/bin:$PATH
  - go mod download

lint:
  stage: test
  script:
    - go install golang.org/x/lint/golint@latest
    - $GOPATH/bin/golint -set_exit_status ./...

test:
  stage: test
  script:
    - go test ./...
    - go vet ./...

build:
  stage: build
  script:
    - go build -o bin/api-go ./cmd/main.go  # Ajuste o caminho conforme sua estrutura
  artifacts:
    paths:
      - bin/api-go

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
    - main
  when: manual