# .gitlab-ci.yml
image: golang:latest

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  GO111MODULE: "on"
  GOLINT_PATH: "$GOPATH/bin/golint"

cache:
  paths:
    - .go/pkg/mod/
    - .go/bin/

stages:
  - test
  - build
  - deploy

before_script:
  - mkdir -p .go
  - export PATH=$GOPATH/bin:$PATH
  - go mod download

lint:
  stage: test
  script:
    - go install golang.org/x/lint/golint@latest
    - $GOPATH/bin/golint -set_exit_status ./...

test:
  stage: test
  script:
    - go test -v -race ./...
    - go vet ./...
  coverage: '/coverage: \d+.\d+% of statements/'

build:
  stage: build
  script:
    - go build -o binary
  artifacts:
    paths:
      - binary

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
    - main
  when: manual